[tool.poetry]
name = "matsuyama"
version = "0.1.0"
description = ""
authors = ["weiwei <wanweiwei07@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
